baseURL: 'https://mahdihasan2005.github.io/test/'
languageCode: 'en-us'
title: 'My New Hugo Site'
theme: PaperMod

params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: facebook
          url: "<link>"
        - name: mastodon
          url: "<link2>"
